#!/bin/bash
#PBS -N wandb_sweep
#PBS -l select=1:ncpus=16:mem=32gb:ngpus=1:gpu_type=L40S
#PBS -l walltime=72:00:00

cd ${PBS_O_WORKDIR}

# Load your Python environment
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate gradual-aacbr

# Set wandb API key
# export WANDB_API_KEY=your_wandb_api_key_here

# Run the wandb agent with dynamic sweep ID
python HPC/run_tuning.py --sweep_id $SWEEP_ID
